Repository wanted-all-clear/tasty-track, pull requests merged in 2024-08, with the labels that each got.

#19 [Feat] 맛집 데이터 수집 기능 구현 및 yml 설정 추가
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/LocalData.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/LocalDataResponse.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/RawRestaurantResponse.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/Result.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RawRestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiService.java
  src/main/java/com/allclear/tastytrack/domain/restraunt/controller/.gitkeep
  src/main/java/com/allclear/tastytrack/domain/restraunt/dto/.gitkeep
  src/main/java/com/allclear/tastytrack/domain/restraunt/entity/.gitkeep
  src/main/java/com/allclear/tastytrack/domain/restraunt/repository/.gitkeep
  src/main/java/com/allclear/tastytrack/domain/restraunt/service/.gitkeep
  src/main/resources/application.yml
Labels: Feat, Chore

#26 [Style] 맛집 원본 관련 데이터 변수명 대문자->소문자로 변경 및 위도, 경도 변수명 수정
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/RawRestaurantResponse.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiService.java
Labels: Style

#31 [Feat] 회원정보 조회 기능
  src/main/java/com/allclear/tastytrack/domain/user/controller/UserController.java
  src/main/java/com/allclear/tastytrack/domain/user/entity/User.java
  src/main/java/com/allclear/tastytrack/domain/user/service/UserService.java
  src/main/java/com/allclear/tastytrack/domain/user/service/UserServiceImpl.java
Labels: Feat

#38 [Chore] Redis 설정 및 사용 방법
  src/main/java/com/allclear/tastytrack/global/config/JpaConfig.java
  src/main/java/com/allclear/tastytrack/global/entity/Timestamped.java
  src/main/resources/application.yml
Labels: Feat, Chore

#33 [Refactor] 맛집 데이터 수집 기능 리팩토링
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/RawRestaurantResponse.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RawRestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiService.java
  src/main/java/com/allclear/tastytrack/global/config/WebSecurityConfig.java
Labels: Fix, Refactor

#43 [Refactor] ApiService > Service-Impl 구조로 리팩토링
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiServiceImpl.java
Labels: Refactor

#46 [Feat] 시군구 csv 데이터 저장 파일 생성
  .github/workflows/create-jira-issue.yml
  src/main/java/com/allclear/tastytrack/domain/region/entity/Region.java
  src/main/resources/application.yml
  src/main/resources/db/data.sql
  src/main/resources/db/region.sql
Labels: Feat

#44 [Feat] 맛집 데이터 전처리 및 저장 기능 구현
  .github/workflows/create-jira-issue.yml
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/Restaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiServiceImpl.java
Labels: Feat

#50 [Chore] Swagger 설정 완료
  build.gradle
  src/main/java/com/allclear/tastytrack/global/config/SwaggerConfig.java
  src/main/java/com/allclear/tastytrack/global/config/WebSecurityConfig.java
Labels: Chore

#52 [Feat] 주소 위도 경도 데이터 수집
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/Coordinate.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/CoordinateAddress.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/CoordinateMeta.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/CoordinateResponse.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/CoordinateRoadAddress.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/Documents.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/service/CoordinateService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/service/CoordinateServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiServiceImpl.java
Labels: Feat

#53 [Feat] 시군구 정보 조회 기능 완료(테스트 포함)
  src/main/java/com/allclear/tastytrack/domain/region/controller/RegionController.java
  src/main/java/com/allclear/tastytrack/domain/region/domain/Region.java
  src/main/java/com/allclear/tastytrack/domain/region/dto/RegionGroupResponse.java
  src/main/java/com/allclear/tastytrack/domain/region/dto/RegionResponse.java
  src/main/java/com/allclear/tastytrack/domain/region/repository/RegionRepository.java
  src/main/java/com/allclear/tastytrack/domain/region/service/RegionService.java
  src/main/java/com/allclear/tastytrack/domain/region/service/RegionServiceImpl.java
  src/main/java/com/allclear/tastytrack/global/config/WebSecurityConfig.java
  src/main/java/com/allclear/tastytrack/global/exception/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/db/data.sql
  src/test/java/com/allclear/tastytrack/domain/region/service/RegionServiceImplTest.java
Labels: Feat, Test

#56 [Refactor] 맛집 데이터 수집 관련 리팩토링, 맛집 가공 엔티티의 위도/경도 타입 변경
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/Restaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/db/data.sql
Labels: Refactor

#57 [Test] 사용자 관련 API 테스트
  src/main/java/com/allclear/tastytrack/domain/auth/UserAuthImpl.java
  src/main/java/com/allclear/tastytrack/domain/user/controller/UserController.java
  src/main/java/com/allclear/tastytrack/domain/user/dto/LoginRequest.java
  src/main/java/com/allclear/tastytrack/domain/user/dto/UserUpdateRequest.java
  src/main/java/com/allclear/tastytrack/domain/user/entity/User.java
  src/main/java/com/allclear/tastytrack/domain/user/service/UserService.java
  src/main/java/com/allclear/tastytrack/domain/user/service/UserServiceImpl.java
  src/test/java/com/allclear/tastytrack/domain/user/controller/UserControllerTest.java
  src/test/java/com/allclear/tastytrack/domain/user/service/TokenVerifyTest.java
  src/test/java/com/allclear/tastytrack/domain/user/service/UserServiceImplTest.java
Labels: Fix, Test

#58 [Feat] 맛집 데이터 전처리 및 저장을 위한 스케줄러 설정
  src/main/java/com/allclear/tastytrack/TastytrackApplication.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/Restaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RawRestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/DataProcessingService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RawDataService.java
  src/main/resources/application.yml
Labels: Feat, Refactor

#65 [Refactor] 영업 상태가 폐업인 맛집 원본 초기 데이터 저장 제외
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RawDataService.java
Labels: Refactor

#62 [Refactor] 데이터 파이프라인 예외처리 보완 및 맛집 원본 Entity 폐업일자 필드 삭제
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/RawRestaurantResponse.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/Restaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/ApiServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/DataProcessingService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RawDataService.java
  src/main/java/com/allclear/tastytrack/global/exception/ErrorCode.java
Labels: Refactor
