Repository wanted-all-clear/tasty-track, pull requests merged in 2024-09, with the labels that each got.

#72 [Style] 인증 URL및 키 값 환경변수로 변경, 주석 추가
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/Coordinate.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/CoordinateResponse.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/dto/Documents.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/coordinate/service/CoordinateServiceImpl.java
Labels: Style

#71 [Feat] 맛집 목록 조회
  build.gradle
  docker-compose.yml
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/RestaurantListRequest.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/com/allclear/tastytrack/global/exception/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/allclear/tastytrack/restaurant/RestaurantControllerTest.java
  src/test/java/com/allclear/tastytrack/restaurant/RestaurantServiceImplTest.java
Labels: Feat

#74 [Refactor] 사용자 관련 API 보완
  build.gradle
  src/main/java/com/allclear/tastytrack/domain/auth/UserAuthImpl.java
  src/main/java/com/allclear/tastytrack/domain/auth/UserDetailsServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/auth/token/JwtTokenUtils.java
  src/main/java/com/allclear/tastytrack/domain/auth/token/RefreshToken.java
  src/main/java/com/allclear/tastytrack/domain/auth/token/RefreshTokenCleanupScheduler.java
  src/main/java/com/allclear/tastytrack/domain/auth/token/RefreshTokenManager.java
  src/main/java/com/allclear/tastytrack/domain/auth/token/RefreshTokenRepository.java
  src/main/java/com/allclear/tastytrack/domain/auth/token/TokenProvider.java
  src/main/java/com/allclear/tastytrack/domain/user/controller/TokenController.java
  src/main/java/com/allclear/tastytrack/global/config/WebSecurityConfig.java
  src/test/java/com/allclear/tastytrack/domain/user/service/TokenVerifyTest.java
Labels: Feat, Refactor, Style

#64 [Feat] 지역 기반 맛집 조회
  docker-compose.yml
  src/main/java/com/allclear/tastytrack/domain/region/controller/RegionController.java
  src/main/java/com/allclear/tastytrack/domain/region/entity/Region.java
  src/main/java/com/allclear/tastytrack/domain/region/repository/RegionRepository.java
  src/main/java/com/allclear/tastytrack/domain/region/service/RegionService.java
  src/main/java/com/allclear/tastytrack/domain/region/service/RegionServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/RestaurantSearch.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/Restaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/review/entity/Review.java
  src/main/java/com/allclear/tastytrack/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/allclear/tastytrack/global/exception/ErrorCode.java
  src/test/java/com/allclear/tastytrack/domain/region/service/RegionServiceImplTest.java
  src/test/java/com/allclear/tastytrack/restaurant/RestaurantServiceImplTest.java
Labels: Fix, Feat, Style

#69 [Feat] 사용자 위치 기반 맛집 조회
  src/main/java/com/allclear/tastytrack/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/dto/RestaurantByUserLocation.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/DataProcessingService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/review/controller/ReviewController.java
  src/main/java/com/allclear/tastytrack/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/user/controller/UserController.java
  src/main/java/com/allclear/tastytrack/domain/user/dto/UserLocationInfo.java
  src/main/java/com/allclear/tastytrack/domain/user/enums/Coordinate.java
  src/main/java/com/allclear/tastytrack/global/exception/ErrorCode.java
  src/test/java/com/allclear/tastytrack/domain/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantServiceImplTest.java
  src/test/java/com/allclear/tastytrack/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/allclear/tastytrack/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/allclear/tastytrack/domain/user/controller/UserControllerTest.java
  src/test/java/com/allclear/tastytrack/domain/user/service/UserServiceImplTest.java
Labels: Feat

#76 [Feat] 디스코드 점심메뉴 추천
  src/main/java/com/allclear/tastytrack/domain/region/repository/RegionRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/webhook/controller/WebhookController.java
  src/main/java/com/allclear/tastytrack/domain/webhook/dto/DiscordMessage.java
  src/main/java/com/allclear/tastytrack/domain/webhook/service/DiscordWebhookService.java
  src/main/java/com/allclear/tastytrack/global/config/WebSecurityConfig.java
  src/main/java/com/allclear/tastytrack/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: Feat

#77 [Refactor] AccessToken 재발급 시 헤더에 담아 반환
  Dockerfile
  docker-compose.yml
  src/main/java/com/allclear/tastytrack/domain/auth/token/RefreshTokenManager.java
  src/main/java/com/allclear/tastytrack/domain/user/controller/TokenController.java
Labels: Refactor

#85 [Refactor] 데이터 파이프라인 성능 개선 스프링 배치 도입
  build.gradle
  src/main/java/com/allclear/tastytrack/domain/batch/config/BatchConfig.java
  src/main/java/com/allclear/tastytrack/domain/batch/config/ScheduleConfig.java
  src/main/java/com/allclear/tastytrack/domain/batch/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/batch/dto/LocalData.java
  src/main/java/com/allclear/tastytrack/domain/batch/dto/LocalDataResponse.java
  src/main/java/com/allclear/tastytrack/domain/batch/dto/RawRestaurantResponse.java
  src/main/java/com/allclear/tastytrack/domain/batch/dto/Result.java
  src/main/java/com/allclear/tastytrack/domain/batch/service/RawDataService.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/entity/RawRestaurant.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/DataProcessingService.java
  src/main/java/com/allclear/tastytrack/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: Refactor

#91 [Refactor] BatchConfig 리팩토링 및 ApiController 엔드포인트 수정
  src/main/java/com/allclear/tastytrack/domain/batch/config/BatchConfig.java
  src/main/java/com/allclear/tastytrack/domain/batch/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RawRestaurantRepository.java
  src/main/java/com/allclear/tastytrack/global/config/WebSecurityConfig.java
Labels: Refactor

#92 [Refactor] 원본 맛집 전처리 시 도로명주소, 위도, 경도가 없고, 지번주소도 조회되지 않는 경우, 가공 맛집 저장에서 제외
  src/main/java/com/allclear/tastytrack/domain/batch/config/BatchConfig.java
  src/main/java/com/allclear/tastytrack/domain/batch/controller/ApiController.java
  src/main/java/com/allclear/tastytrack/domain/batch/listener/JobCompletionNotificationListener.java
  src/main/java/com/allclear/tastytrack/domain/batch/service/RawDataService.java
Labels: Refactor

#94 [Feat] 디스코드 점심메뉴 추천
  src/main/java/com/allclear/tastytrack/domain/region/repository/RegionRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/allclear/tastytrack/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/com/allclear/tastytrack/domain/webhook/controller/WebhookController.java
  src/main/java/com/allclear/tastytrack/domain/webhook/dto/DiscordMessage.java
  src/main/java/com/allclear/tastytrack/domain/webhook/service/DiscordWebhookService.java
  src/main/java/com/allclear/tastytrack/global/config/RedisConfig.java
  src/main/java/com/allclear/tastytrack/global/exception/ErrorCode.java
  src/main/java/com/allclear/tastytrack/global/util/RedisUtil.java
Labels: Feat
